baseURL: "https://huntears.com/"
title: huntears' den
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "huntears' den"
  description: "A simple website for me to post stuff"
  keywords: [Blog, Portfolio, PaperMod, Hugo, Markdown, Technology, C++, C, Minecraft]
  author: huntears
  images: ["https://huntears.com/img/pfp.webp"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    favicon: "/img/pfp.webp"

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "huntears' den"
    subtitle: "A hangout for random stuff I think of and do"
    imageUrl: "/img/pfp.webp"
    imageWidth: 240
    imageHeight: 240
    imageTitle: "My profile picture, as my OC with long black hair doing a peace sign"
    buttons:
      - name: Posts
        url: post
      - name: About
        url: about

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: mastodon
      url: "https://fosstodon.org/@huntears"
    - name: gitlab
      url: "https://gitlab.com/huntears"
    - name: github
      url: "https://github.com/huntears"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: posts
      url: post
      weight: 10
    - identifier: about
      name: about
      url: about
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
